In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/Edited_Stocks.csv')  

In [ ]:
df

Name    Last    High     Low   Chg  Chg_per  Volume  \
0                 ABC Gas Intl   15.97   15.97   15.97  0.00     0.00       0   
1                  APM Finvest  110.80  115.40  109.00 -1.05    -0.94   22450   
2                 Ace Engitech   16.94   16.94   16.94  0.80     4.96     100   
3               Ace Integrated   33.15   33.15   33.15  0.00     0.00       0   
4          Alfavision Overseas  149.50  149.65  149.50  0.20     0.13    3770   
..                         ...     ...     ...     ...   ...      ...     ...   
99   W.S. Industries India Ltd   13.10   13.10   13.10  0.00     0.00       0   
100  W.S. Industries India Ltd   13.23   13.23   13.23  0.00     0.00       0   
101    Welterman International    7.71    7.71    7.71  0.00     0.00       0   
102             Yarn Syndicate    8.16    8.16    8.16  0.38     4.88     650   
103            iStreet Network    3.90    3.90    3.71  0.00     0.00       0   

         Time  
0      28-Jun  
1    09:59:55  
2    09:23:43  
3      28-Jun  
4    09:52:21  
..        ...  
99     27-Jun  
100    27-Jun  
101    28-Jun  
102  09:55:54  
103    27-Jun  

[104 rows x 8 columns]

In [ ]:
df.head()

Name    Last    High     Low   Chg  Chg_per  Volume  \
0         ABC Gas Intl   15.97   15.97   15.97  0.00     0.00       0   
1          APM Finvest  110.80  115.40  109.00 -1.05    -0.94   22450   
2         Ace Engitech   16.94   16.94   16.94  0.80     4.96     100   
3       Ace Integrated   33.15   33.15   33.15  0.00     0.00       0   
4  Alfavision Overseas  149.50  149.65  149.50  0.20     0.13    3770   

       Time  
0    28-Jun  
1  09:59:55  
2  09:23:43  
3    28-Jun  
4  09:52:21

In [ ]:
df.dtypes

Name        object
Last       float64
High       float64
Low        float64
Chg        float64
Chg_per    float64
Volume       int64
Time        object
dtype: object

In [ ]:
df.drop(df[df['High'] >= 100].index, inplace = True)

In [ ]:
df

Name   Last   High    Low   Chg  Chg_per  Volume  \
0                 ABC Gas Intl  15.97  15.97  15.97  0.00     0.00       0   
2                 Ace Engitech  16.94  16.94  16.94  0.80     4.96     100   
3               Ace Integrated  33.15  33.15  33.15  0.00     0.00       0   
5     Ambar Protein Industries  52.80  52.80  52.80  2.50     4.97      20   
8          Balgopal Commercial  16.20  16.20  16.20  0.00     0.00       0   
..                         ...    ...    ...    ...   ...      ...     ...   
99   W.S. Industries India Ltd  13.10  13.10  13.10  0.00     0.00       0   
100  W.S. Industries India Ltd  13.23  13.23  13.23  0.00     0.00       0   
101    Welterman International   7.71   7.71   7.71  0.00     0.00       0   
102             Yarn Syndicate   8.16   8.16   8.16  0.38     4.88     650   
103            iStreet Network   3.90   3.90   3.71  0.00     0.00       0   

         Time  
0      28-Jun  
2    09:23:43  
3      28-Jun  
5    09:26:50  
8      27-Jun  
..        ...  
99     27-Jun  
100    27-Jun  
101    28-Jun  
102  09:55:54  
103    27-Jun  

[84 rows x 8 columns]

In [ ]:
df.dropna()

Name   Last   High    Low   Chg  Chg_per  Volume  \
0                 ABC Gas Intl  15.97  15.97  15.97  0.00     0.00       0   
2                 Ace Engitech  16.94  16.94  16.94  0.80     4.96     100   
3               Ace Integrated  33.15  33.15  33.15  0.00     0.00       0   
5     Ambar Protein Industries  52.80  52.80  52.80  2.50     4.97      20   
8          Balgopal Commercial  16.20  16.20  16.20  0.00     0.00       0   
..                         ...    ...    ...    ...   ...      ...     ...   
99   W.S. Industries India Ltd  13.10  13.10  13.10  0.00     0.00       0   
100  W.S. Industries India Ltd  13.23  13.23  13.23  0.00     0.00       0   
101    Welterman International   7.71   7.71   7.71  0.00     0.00       0   
102             Yarn Syndicate   8.16   8.16   8.16  0.38     4.88     650   
103            iStreet Network   3.90   3.90   3.71  0.00     0.00       0   

         Time  
0      28-Jun  
2    09:23:43  
3      28-Jun  
5    09:26:50  
8      27-Jun  
..        ...  
99     27-Jun  
100    27-Jun  
101    28-Jun  
102  09:55:54  
103    27-Jun  

[84 rows x 8 columns]

In [ ]:
x= df.iloc[:,:-1].values  

In [ ]:
x

array([['ABC Gas Intl', 15.97, 15.97, 15.97, 0.0, 0.0, 0],
       ['Ace Engitech', 16.94, 16.94, 16.94, 0.8, 4.96, 100],
       ['Ace Integrated', 33.15, 33.15, 33.15, 0.0, 0.0, 0],
       ['Ambar Protein Industries', 52.8, 52.8, 52.8, 2.5, 4.97, 20],
       ['Balgopal Commercial', 16.2, 16.2, 16.2, 0.0, 0.0, 0],
       ['Beekay Niryat', 45.55, 45.55, 45.55, 0.0, 0.0, 0],
       ['Bheema Cements', 98.2, 98.25, 98.2, 0.0, 0.0, 0],
       ['Blue Chip India Ltd', 0.49, 0.49, 0.49, 0.0, 0.0, 0],
       ['Capfin India Ltd', 9.01, 9.01, 9.01, 0.42, 4.89, 1],
       ['Chitradurga Spintex', 21.1, 21.1, 21.1, 0.0, 0.0, 0],
       ['DSJ Keep Learning', 1.9, 1.9, 1.9, 0.09, 4.97, 1500],
       ['Datasoft Application', 3.65, 3.65, 3.65, 0.0, 0.0, 0],
       ['Deccan Polypacks', 5.15, 5.15, 5.15, 0.0, 0.0, 0],
       ['Dhruva Capital Services', 9.59, 9.59, 9.59, 0.0, 0.0, 0],
       ['Diamond Power Infrastructure', 1.85, 1.85, 1.85, 0.0, 0.0, 0],
       ['Dynamic Portfolio Management & Services', 2

In [ ]:
y= df.iloc[:,3].values

In [ ]:
y

array([15.97, 16.94, 33.15, 52.8 , 16.2 , 45.55, 98.2 ,  0.49,  9.01,
       21.1 ,  1.9 ,  3.65,  5.15,  9.59,  1.85, 20.55,  6.65,  5.6 ,
        4.25, 38.8 , 18.  , 74.  , 39.9 ,  2.36, 25.65,  5.68, 18.1 ,
       18.55,  9.78,  4.44, 21.45,  2.62,  2.4 ,  0.42,  5.28, 44.25,
        9.28,  4.73,  1.15, 25.9 , 78.65,  0.52, 23.5 , 61.95,  3.47,
       28.2 , 65.1 , 57.45,  0.49,  8.27, 27.95,  2.4 ,  3.5 , 21.04,
       70.2 , 69.25, 17.  , 11.2 , 50.2 , 15.12, 33.  ,  0.58, 21.44,
        3.45, 19.45, 19.59, 10.04, 28.85, 60.05,  1.72, 14.71, 24.55,
       14.88,  9.53,  0.38, 18.9 ,  2.62, 27.4 ,  2.23, 13.1 , 13.23,
        7.71,  8.16,  3.71])

In [ ]:
pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
x= df.iloc[:,:-1].values  

In [ ]:
x

array([['ABC Gas Intl', 15.97, 15.97, 15.97, 0.0, 0.0, 0],
       ['Ace Engitech', 16.94, 16.94, 16.94, 0.8, 4.96, 100],
       ['Ace Integrated', 33.15, 33.15, 33.15, 0.0, 0.0, 0],
       ['Ambar Protein Industries', 52.8, 52.8, 52.8, 2.5, 4.97, 20],
       ['Balgopal Commercial', 16.2, 16.2, 16.2, 0.0, 0.0, 0],
       ['Beekay Niryat', 45.55, 45.55, 45.55, 0.0, 0.0, 0],
       ['Bheema Cements', 98.2, 98.25, 98.2, 0.0, 0.0, 0],
       ['Blue Chip India Ltd', 0.49, 0.49, 0.49, 0.0, 0.0, 0],
       ['Capfin India Ltd', 9.01, 9.01, 9.01, 0.42, 4.89, 1],
       ['Chitradurga Spintex', 21.1, 21.1, 21.1, 0.0, 0.0, 0],
       ['DSJ Keep Learning', 1.9, 1.9, 1.9, 0.09, 4.97, 1500],
       ['Datasoft Application', 3.65, 3.65, 3.65, 0.0, 0.0, 0],
       ['Deccan Polypacks', 5.15, 5.15, 5.15, 0.0, 0.0, 0],
       ['Dhruva Capital Services', 9.59, 9.59, 9.59, 0.0, 0.0, 0],
       ['Diamond Power Infrastructure', 1.85, 1.85, 1.85, 0.0, 0.0, 0],
       ['Dynamic Portfolio Management & Services', 2

In [ ]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)  

In [ ]:
from sklearn.preprocessing import StandardScaler  

In [ ]:
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)  

In [ ]:
x_test= st_x.transform(x_test)  

In [ ]:
x_train

array([[ 1.28723824e+00, -4.34726776e-01, -4.37789771e-01,
        -4.32075479e-01,  9.88366161e-02,  1.47891870e+00,
        -1.66207045e-01],
       [ 2.64746422e-01, -8.60002665e-01, -8.61876950e-01,
        -8.62955807e-01, -5.00745672e-01, -7.18989545e-01,
        -1.98881551e-01],
       [ 1.33169441e+00, -8.65177483e-01, -8.67037302e-01,
        -8.68198820e-01, -5.00745672e-01, -7.18989545e-01,
        -1.98881551e-01],
       [ 1.68734374e+00, -6.99583331e-01, -7.01906012e-01,
        -7.09478522e-01, -5.00745672e-01, -7.18989545e-01,
        -1.98881551e-01],
       [ 7.53764251e-01, -8.55768724e-01, -8.57654843e-01,
        -8.58666069e-01, -5.00745672e-01, -7.18989545e-01,
        -1.98881551e-01],
       [-4.64467408e-02, -8.58591352e-01, -8.60469581e-01,
        -8.61525894e-01, -5.00745672e-01, -7.18989545e-01,
        -1.98881551e-01],
       [ 8.42676583e-01, -7.20753038e-01, -7.23016546e-01,
        -7.21871098e-01, -3.00884910e-01,  1.29723677e+00,
        -1.7100819

In [ ]:
x_test= st_x.transform(x_test)  

In [ ]:
x_test

array([[-1.75760941, -0.87712495, -0.8791686 , -0.87982513, -1.16794175,
        -1.03759298, -0.1988842 ],
       [-1.73982225, -0.75053457, -0.75328491, -0.74987626, -4.36348772,
        -1.47744216, -0.19888385],
       [-1.7338932 , -0.78273545, -0.78453576, -0.78781588,  8.32993097,
         0.75125791, -0.19883966],
       [-1.72005874, -0.86262902, -0.86475359, -0.86505821, -1.16794175,
        -1.03759298, -0.1988842 ],
       [-1.77144386, -0.8360716 , -0.83746412, -0.83790981,  1.13995255,
        -0.37781922, -0.19888198],
       [-1.71412969, -0.75805918, -0.76076751, -0.76907326,  5.13438501,
        -0.06560485, -0.19884691],
       [-1.80899453, -0.85123146, -0.85341966, -0.85324468, -1.16794175,
        -1.03759298, -0.1988842 ],
       [-1.71215334, -0.88697333, -0.888962  , -0.88993479, -1.16794175,
        -1.03759298, -0.1988842 ],
       [-1.76353846, -0.88201594, -0.88403228, -0.88743577,  0.44758426,
        -0.06364124, -0.19862097],
       [-1.79713642, -0.9046